name: Merge changes into block_things

on:
    workflow_dispatch:
    schedule:
        - cron: "0 14 * * *"
jobs:
    update_branch:
        runs-on: ubuntu-latest
        steps:
            - name: sync fork
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: gh repo sync amp287/firefox-android -b main
            - name: checkout
              uses: actions/checkout@v2
              with:
                ref: main
                fetch-depth: 0
            - name: merge_main_into_block_things
              run: |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"
                git pull
                git checkout block_things
                git merge main
                git push
                

            


    
